name: Terraform CICD Pipeline for Deploying AWS resources.
run-name: ${{ github.actor }} has triggerd the pipeline.

on:
  push:
    branchs:
      - "main"

env: 
  AWS_ACCESS_KEY: $ {{ secrets.AWS_ACCESS_KEY }} 
  AWS_SECRET_ACCESS_KEY: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infrastrucutre:
    name: Terraform-CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actins/checkout@v2
        #https://github.com/marketplace/actions/checkout
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        #https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform-aws-github-actions-Project
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform-aws-github-actions-Project
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./terraform-aws-github-actions-Project
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./terraform-aws-github-actions-Project